export const services = [
  {
    id: 5,
    name: "AI & LLM Solutions",
    des: "Harness the power of large language models and retrieval-augmented generation to transform your business operations. From intelligent document processing to custom knowledge bases, we build AI systems that understand your domain and deliver measurable results.",
    img: "/img/bannerBg.png",
  },
  {
    id: 6,
    name: "AI Chatbot Development",
    des: "Deploy intelligent conversational agents that handle customer inquiries, automate workflows, and scale your support operations. Our custom chatbots integrate with your existing systems and learn from your data to provide accurate, context-aware responses.",
    img: "/img/bannerBg.png",
  },
  {
    id: 1,
    name: "Website Development",
    des: "Turn your digital vision into reality with our expert website development. We create user-centric, visually appealing, and functional websites tailored to elevate your online presence and engage your audience effectively",
    img: "/img/webDev.jpeg",
  },
  {
    id: 2,
    name: "Mobile App Development",
    des: "Realize your app vision with our expert development services. We craft user-centric, visually appealing, and functional apps tailored to enhance your digital presence and engage your audience effectively.",
    img: "/img/aapdev.jpeg",
  },
  {
    id: 3,
    name: "Aws Cloud Management",
    des: "Elevate your cloud experience with our AWS management services. We specialize in optimizing, securing, and managing AWS resources, ensuring a seamless and efficient cloud infrastructure aligned with your business objectives.",
    img: "/img/aws.avif",
  },
  {
    id: 4,
    name: "Wordpress - Woocommerce",
    des: "Enhance your digital presence with our WordPress and WooCommerce development expertise. We create dynamic, user-friendly websites tailored to your needs, ensuring a powerful online platform that elevates your brand and engages your audience effectively",
    img: "/img/wordpress.jpeg",
  },
];

export const pricing = [
  {
    id: 5,
    name: "AI & LLM Solutions",
    img: "/img/bannerBg.png",
    originalPrice: "$150/hr",
    startingPrice: "$80/hr",
    discount: "47% OFF",
    badge: "Most Popular",
    whatYouGet: [
      "RAG pipeline setup",
      "Custom knowledge base",
      "LLM fine-tuning & integration",
      "Vector database setup",
      "Prompt engineering",
      "API integration & deployment",
    ],
    tittle: "Enterprise AI Solutions",
    dec: "RAG systems, document intelligence, custom LLM integrations, AI-powered search, automated content generation, and workflow automation.",
    deliveryTime: "2–4 weeks",
    revision: "Iterative",
    clients: [],
  },
  {
    id: 6,
    name: "AI Chatbot Development",
    img: "/img/bannerBg.png",
    originalPrice: "$100/hr",
    startingPrice: "$60/hr",
    discount: "40% OFF",
    badge: "High Demand",
    whatYouGet: [
      "Custom trained chatbot",
      "Multi-channel deployment",
      "Analytics dashboard",
      "Human handoff flow",
      "Knowledge base integration",
      "Continuous learning",
    ],
    tittle: "Intelligent Chatbot Systems",
    dec: "Customer support bots, internal knowledge assistants, lead qualification bots, appointment scheduling, and FAQ automation.",
    deliveryTime: "1–3 weeks",
    revision: "Iterative",
    clients: [],
  },
  {
    id: 1,
    name: "Website Development",
    img: "/img/webdev1.jpeg",
    originalPrice: "$499",
    startingPrice: "$199",
    discount: "60% OFF",
    badge: "Best Value",
    whatYouGet: [
      "3–5 Sections",
      "Mobile & Tablet Responsive",
      "SEO Ready",
      "Built with React, Next.js, Tailwind CSS",
      "Fast Loading & Optimized",
      "1 Round of Revisions",
    ],
    tittle: "Single Page Application",
    dec: "Perfect for company pages, personal portfolios, landing pages, and single-page blogs.",
    deliveryTime: "2–3 days",
    revision: "1 time",
    clients: [
      {
        id: 1,
        name: "Tata",
        url: "https://www.starquik.com/",
      },
      {
        id: 2,
        name: "Fanseb",
        url: "https://fanseb.com/",
      },
      {
        id: 3,
        name: "Socialee",
        url: "https://www.socialee.shop/en",
      },
      {
        id: 4,
        name: "Koshish Family",
        url: "https://koshishfamily.org/",
      },
    ],
  },
  {
    id: 2,
    name: "Mobile App Development",
    img: "/img/appdev1.png",
    originalPrice: "$75/hr",
    startingPrice: "$35/hr",
    discount: "53% OFF",
    badge: "Limited Time",
    whatYouGet: [
      "Interactive UI/UX Design",
      "iOS & Android Support",
      "Built with React Native & Expo",
      "Fast & Dynamic Performance",
      "API Integration",
      "App Store Ready",
    ],
    tittle: "Cross-Platform App Development",
    dec: "Food delivery apps, social media apps, travel apps, ticket booking, LMS platforms, and business tools.",
    deliveryTime: "1–4 weeks",
    revision: "1 time",
    clients: [],
  },
  {
    id: 3,
    name: "AWS Cloud Management",
    img: "/img/aws1.avif",
    originalPrice: "$65/hr",
    startingPrice: "$30/hr",
    discount: "54% OFF",
    badge: "New Launch",
    whatYouGet: [
      "EC2 Instance Setup & Management",
      "Monitoring & Alerts",
      "Domain Routing with Route 53",
      "WordPress Hosting",
      "Database Setup & Management",
      "SSL & Security Configuration",
    ],
    tittle: "AWS Cloud Management",
    dec: "Managing EC2, Amplify, RDS, S3, domain routing, and WordPress hosting on AWS infrastructure.",
    deliveryTime: "1–3 days",
    revision: "1 time",
    clients: [
      {
        id: 1,
        name: "Novasie",
        url: "https://novasie.com",
      },
      {
        id: 2,
        name: "Fgito",
        url: "https://fgito.com",
      },
    ],
  },
  {
    id: 4,
    name: "WordPress & WooCommerce",
    img: "/img/wordpress1.jpeg",
    originalPrice: "$45/hr",
    startingPrice: "$20/hr",
    discount: "55% OFF",
    badge: "Starter Friendly",
    whatYouGet: [
      "Custom Page Design",
      "Mobile & Tablet Responsive",
      "Elementor Page Builder",
      "WooCommerce Setup",
      "Plugin Configuration",
      "Speed Optimization",
    ],
    tittle: "WordPress Development",
    dec: "Business portfolios, blogs, school websites, personal websites, booking sites, and e-commerce stores.",
    deliveryTime: "2–5 days",
    revision: "1 time",
    clients: [
      {
        id: 1,
        name: "Novasie",
        url: "https://novasie.com",
      },
      {
        id: 2,
        name: "Lotus Preschool",
        url: "https://www.lotuspreschool.co.za/",
      },
    ],
  },
];

export const testimonial = [
  {
    id: 1,
    dec: "Ravi built our product landing pages and integrated Stripe payments — the whole thing took about three weeks, which was faster than I expected honestly. We went back and forth a lot on the mobile layout in the first few days because I kept changing my mind, but he was patient about it and didn't charge extra for the revisions. The site loads fast and we've had zero issues since launch. Already hired him for a second project.",
    name: "Jason Miller",
    company: "E-commerce Startup",
    country: "🇺🇸 US",
    service: "Website Development",
  },
  {
    id: 2,
    dec: "We needed a fairly simple booking app for our salon — nothing overly complex, but it had to sync with Google Calendar and handle payments. He delivered a working prototype in about four weeks. He was upfront when something was going to take longer than planned, which I appreciated — our previous developer used to just go quiet for days. There were a couple of minor UI bugs after the first build but he sorted them within a day. Quite happy with how it turned out.",
    name: "Sophie Harrington",
    company: "Local Salon Business",
    country: "🇬🇧 UK",
    service: "Mobile App Development",
  },
  {
    id: 3,
    dec: "We'd actually tried building a chatbot ourselves before hiring him, and it was a mess. He rebuilt it from scratch and connected it to our knowledge base so it actually pulls relevant answers. It's not perfect — it still stumbles on some edge cases — but our support team says it's handling about 40% of incoming queries without human intervention now. He also set up a dashboard so we can see what questions the bot gets stuck on, which was a nice touch I didn't originally ask for.",
    name: "Marcus Webb",
    company: "Marketing Agency",
    country: "🇺🇸 US",
    service: "AI Chatbot Development",
  },
  {
    id: 4,
    dec: "We were running everything on a single EC2 instance — not ideal, I know — and he helped us set up proper architecture with load balancing and auto-scaling. Our AWS bill actually went down about 30% because he right-sized our instances. The migration took a weekend and we had maybe 20 minutes of downtime total. Only thing I'd say is his initial time estimate was a bit optimistic — said 3 days, took closer to 5 — but the end result was solid. Would use him again for sure.",
    name: "Liam Nguyen",
    company: "SaaS Company",
    country: "🇦🇺 Australia",
    service: "AWS Cloud Management",
  },
  {
    id: 5,
    dec: "I needed a clean WordPress site for my real estate business — property listings, contact form, IDX integration. He set the whole thing up in about 10 days. He picked a lightweight theme that loads fast, which I specifically asked for because my last site was painfully slow on mobile. He also showed me how to add new listings myself so I don't have to go back to him for every little update. Probably the best money I've spent on my business this year.",
    name: "Sandra Brooks",
    company: "Real Estate Agency",
    country: "🇺🇸 US",
    service: "WordPress Development",
  },
  {
    id: 6,
    dec: "We hired him to customise our Shopify store — specifically the product filtering and a custom checkout flow for B2B customers. He understood the requirements after one call. The work was delivered on schedule and he was always available on Slack during our overlapping hours. One minor issue: the responsive design on tablet wasn't perfect on first delivery, but he fixed it the same day. We will likely work with him again when we expand to the German market.",
    name: "Anders Kristiansen",
    company: "E-commerce Company",
    country: "🇩🇰 Denmark",
    service: "Website Development",
  },
  {
    id: 7,
    dec: "He built our workout tracking app in React Native — it needed to work on both iOS and Android and sync with Apple Health. He was honest early on that the Apple Health integration would be tricky, and it did take longer than the rest of the build, but he got it working. We communicate mostly through Slack and have a weekly Zoom call. We launched on both app stores about 6 weeks after starting. Nothing fancy about the UI but it works well and users haven't reported major bugs.",
    name: "Tyler Simmons",
    company: "Fitness Startup",
    country: "🇺🇸 US",
    service: "Mobile App Development",
  },
  {
    id: 8,
    dec: "We needed our WordPress site updated — it looked quite dated honestly — and we also wanted a simple chatbot that could answer basic questions so the reception team isn't fielding the same calls all day. He handled both. The chatbot was trained on our FAQ document and handles common enquiries quite well. The whole project cost less than what one agency quoted us just for the chatbot. Usually replied within a couple of hours even with the time difference. Would recommend.",
    name: "Claire Whitfield",
    company: "Law Firm",
    country: "🇬🇧 UK",
    service: "WordPress + AI Chatbot",
  },
];
